INSERT INTO product (name, price) VALUES ('Vizio 50-inch Class V-Series 4K UHD LED Smart TV', 248.99);
INSERT INTO product (name, price) VALUES ('Amazon Fire TV 50" 4-Series 4K UHD smart TV', 290.55);
INSERT INTO product (name, price) VALUES ('Sony Bravia 55-inch 4K X90K TV', 798.0);
INSERT INTO product (name, price) VALUES ('Samsung 98-Inch Class QLED 4K Q80C Series Smart TV', 4998);
INSERT INTO product (name, price) VALUES ('Apple AirPods (2nd Generation)', 80.99);
INSERT INTO product (name, price) VALUES ('Hkerr Wireless Earbuds', 10);
INSERT INTO product (name, price) VALUES ('Tozo T6 True Wireless Earbuds', 21.5);
INSERT INTO product (name, price) VALUES ('Sony WH-XB910N Noise Cancelling Headphones', 118);
INSERT INTO product (name, price) VALUES ('Apple AirPods Pro (2nd Generation)', 190);
INSERT INTO product (name, price) VALUES ('Apple 2020 MacBook Air Laptop', 750.99);